name: Manual install

on:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      run: git clone ${{ github.repository_url }} .

    - name: Set up Node.js
      run: |
        curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
        sudo apt-get install -y nodejs

    - name: Install dependencies
      run: npm install
